### ISSUE TITLE
Bug in de zoekfunctie 

### ISSUE THREAD

**Issue by hakkas** [nloomans/rooster.hetmml.nl#14]
Ik heb waarschijnlijk  een bug ontdekt in de zoekfunctie. Zo kun je hem reproduceren:

1) Ga eerst naar een willekeurige rooster. Laten we zeggen het rooster van AKH
2) Navigeer vervolgens naar een week waarvoor geen rooster is
3) Zoek vervolgens naar een ander rooster: dit kan dat niet.

Workaround: Gewoon refreshen.

Ik gebruik de volgende versie van Chrome: Versie 60.0.3112.113 (Officiële build) (64-bits)

**Comment by nloomans** [comment]
Thanks!
